#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_dvl.dvl_client import DvlClient

plugin = 'rqt_dvl.dvl_client.DvlClient'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin,
                   plugin_argument_provider=DvlClient.add_arguments))
