#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_vision.VisionStarter import VisionStarter

plugin = 'rqt_vision.VisionStarter.VisionStarter'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
