#!/usr/bin/env python

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    pass

main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='rqt_mapping_client/MappingClient',
    plugin_argument_provider=add_arguments))

