#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_mapping_client.mapping_client import MappingClient

plugin = 'rqt_mapping_client.mapping_client.MappingClient'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin,
                   plugin_argument_provider=MappingClient.add_arguments))
